rootpath: /data/hongbang/.cogagent/

openqa:
  model_path: openqa/bert-base-mrc-openqa.pt
  retriever_model_file: openqa/retriever/bert-base-encoder.cp
  retriever_index_path: openqa/retriever/index/
  wiki_passages: openqa/wiki_passages/psgs_w100.tsv


dialogue_safety:
  classifier_path: dialogue_safety/classifiers/

sticker:
  vocab_path: sticker/chinese_gossip_dialog/raw_data/vocab.txt
  model_path: sticker/chinese_gossip_dialog/raw_data/
  sticker_model_path: sticker/sticker_model.pt
  id2img_path: sticker/mm_dialog/raw_data/id2img.json
  image_path: sticker/mm_dialog/raw_data/meme_set/